[package]
name = "todo-hunter"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tdhunt"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
git2 = { version = "0.20.3" }
